version: '3.0'

services:

  # Container A
  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    volumes:
      - ./redis-volume:/data
    networks:
      - app-network

  # Container B
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    networks:
      - app-network
    depends_on:
      - redis

  # Container C and D
  backend:
    build: ./backend/src
    container_name: backend
    networks:
      - app-network
    depends_on:
      - redis
     
  # Container E
  app:
    build: ./frontend
    networks: 
      - app-network
    depends_on: 
      - backend
    ports: 
      - '3000:3000'
    command: npm start

networks:
  app-network: